# TODO: Cache policy to pull, see https://docs.gitlab.com/ee/ci/yaml/#cache-policy

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/
  - dist/

stages:
- build
- integration
- test
- deploy

build-lib:
  image: node
  stage: build
  script:
  - npm ci
  - npm run build:lib
  artifacts:
    expire_in: 1 week
    paths:
    - dist/@w11k/angular-sticky-things

build-demo:
  image: node
  dependencies:
  - build-lib
  stage: integration
  script:
  - npm ci
  - npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - dist/angular-sticky-things-demo

#
#test-lib:
#  image: trion/ng-cli-karma
#  stage: test
#  script:
#  - npm run test:lib
#
#test-demo:
#  image: trion/ng-cli-karma
#  dependencies:
#  - build-lib
#  stage: test
#  script:
#  - npm run test

publish-demo:
  image: node
  stage: deploy
  dependencies:
  - build-lib
  - build-demo
  only:
  - master
  - web
  script:
  - git push https://${GITHUB_TOKEN}@github.com/w11k/angular-sticky-things master
  - npx ngh --dir=dist/angular-sticky-things-demo --message=\"updates demo\" --repo=https://${GITHUB_TOKEN}@github.com/w11k/angular-sticky-things


publish:
  image: node:alpine
  stage: deploy
  dependencies:
  - build-lib
  only:
  - tags
  script:
  - cd dist/@w11k/angular-sticky-things
  - cp ../../../README.md .
  - cp ../../../LICENSE .
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
  - npm publish --access=public


